### ISSUE TITLE
[joss-review] problem with shapelets-test on windows

### ISSUE THREAD

**Issue by Anshuman5** [uw-comphys/shapelets#20]
hello, thank you for developing this software. In general, this is a very well documented code, with necessary instructions provided on running this software. The installation and `shapelets-test` functionality work well in mac os. However, there seems to be issue with shapelets-test on Windows system. Please see the error log below when running the `shapelets-test` on Windows:

```python
Traceback (most recent call last):
  File "/home/anshuman/.local/bin/shapelets-test", line 5, in <module>
    from shapelets.entry_points import run_tests
  File "/home/anshuman/.local/lib/python3.8/site-packages/shapelets/__init__.py", line 19, in <module>
    from .entry_points import *
  File "/home/anshuman/.local/lib/python3.8/site-packages/shapelets/entry_points.py", line 22, in <module>
    from .run import *
  File "/home/anshuman/.local/lib/python3.8/site-packages/shapelets/run.py", line 26, in <module>
    from .astronomy.galaxy import *
  File "/home/anshuman/.local/lib/python3.8/site-packages/shapelets/astronomy/__init__.py", line 18, in <module>
    from .galaxy import *
  File "/home/anshuman/.local/lib/python3.8/site-packages/shapelets/astronomy/galaxy.py", line 28, in <module>
    from .misc import *
  File "/home/anshuman/.local/lib/python3.8/site-packages/shapelets/astronomy/misc.py", line 27, in <module>
    def decompose_analytic(image: np.ndarray, n_max: int, beta: float, centroid: np.ndarray, nspace: list[tuple[int, int]]=None) -> np.ndarray:
TypeError: 'type' object is not subscriptable
```  
To replicate this issue follow the instructions for installation on the Windows [here](https://github.com/uw-comphys/shapelets/tree/main).

**Comment by mptino** [comment]
Hello - @Abaacus and I just went through the Windows installation process and did not encounter the same issue...

We believe it may be due to the python version (3.8) used when this issue was encountered. Please retry the entry point after updating to python 3.10 and reinstalling the shapelets package. The commands to do this are given here,

`sudo apt-get purge --auto-remove python3.8`

`sudo apt-get update`

`sudo apt install python3.10`

Then from step 7 of the Windows instructions, `pip3 install .` from the topmost shapelets directory. You can now retry the entry point `shapelets-test`

**Comment by nasserma** [comment]
@Anshuman5  I just merged-in Matthew's improvements to the main branch, please let me know if they address your issue.

**Comment by nasserma** [comment]
@Anshuman5 I just merged-in Abbas's additional unit tests (for the astronomy sub-module) to the main branch. At this point we think this issue is resolved, but wait for your confirmation.

**Comment by Anshuman5** [comment]
@nasserma issue resolved.
